### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 17876380171** [Licoy/ChatGPT-Midjourney#10]
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/65943853/c05688fb-bd22-46ad-979c-937672d297c2)
lian连接超时

**Comment by Licoy** [comment]
很明显，你的proxy api并没有配置正确，请仔细检查核验

**Comment by 17876380171** [comment]
在哪设置proxy api

**Comment by 17876380171** [comment]
我是跟着docker教程部署的

**Comment by Licoy** [comment]
请仔细看文档，里面尽可能说的详细了，有疑问可以进入交流群

**Comment by white-elephant-li** [comment]
这个开个全局代理，或者设置代理就解决了

**Comment by 17876380171** [comment]
是在部署的服务器设置代理吗

**Comment by 17876380171** [comment]
代理弄好啦，但是配了mjproxy
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/65943853/ff27a633-9381-406d-90eb-629d28ad12fd)
haichu还出现这个问题，是什么原因呢

**Comment by white-elephant-li** [comment]
你mj代理配的是8080端口嘛，而且还是外面的ip，

**Comment by white-elephant-li** [comment]
首先这些环境都在外面，肯定需要代理，你服务器是国内的，服务器肯定就需要代理，服务器需要代理，就要配置代理

**Comment by ruanmus** [comment]
我服务器没有代理工具的，chatgpt我是用的代理网址，所以画画报500是因为midourney那个后端也要代理吗
