### ISSUE TITLE
[Bug] cloudflare部署报错

### ISSUE THREAD

**Issue by suwubee** [Licoy/ChatGPT-Midjourney#106]
17:21:39.403	Installing project dependencies: pnpm install
17:21:40.309	 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.autoInstallPeers" configuration doesn't match the value found in the lockfile
17:21:40.310	
17:21:40.310	Update your lockfile using "pnpm install --no-frozen-lockfile"
17:21:40.360	Error: Exit with error code: 1
17:21:40.360	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
17:21:40.361	    at Object.onceWrapper (node:events:652:26)
17:21:40.364	    at ChildProcess.emit (node:events:537:28)
17:21:40.365	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
17:21:40.371	Failed: build command exited with code: 1
17:21:41.222	Failed: error occurred while running build command

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
