### ISSUE TITLE
[Bug] https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/  这路径是否 已经失效了 所有emoji都不显示

### ISSUE THREAD

**Issue by wwlmm** [Licoy/ChatGPT-Midjourney#109]
[Bug] https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/  这路径是否 已经失效了 所有emoji都不显示

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
直接收到打开
https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/1f603.png 等地址 都不显示 emoji
**如何复现**
https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/1f603.png 等地址 都不显示 emoji

**截图**
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/23204809/8185d7d1-c611-4cf2-87f3-fa2d4ba42b8e)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/23204809/13f94f7a-d871-4af6-b0cf-50f08464ded4)

**一些必要的信息**
 - 系统： macos 14
 - 浏览器： chrome, safari，edge
 - 版本： 最新版本
 - 部署方式：vercel、docker

**Comment by willTerner** [comment]
This link can work. https://cdnjs.cloudflare.com/ajax/libs/emoji-datasource-apple/15.0.1/img/apple/64/

**Comment by Licoy** [comment]
v3.2.2 已修复
