### ISSUE TITLE
不算Bug，但是不是特别人性化

### ISSUE THREAD

**Issue by white-elephant-li** [Licoy/ChatGPT-Midjourney#11]
1.关键词切换提议
我在使用的时候/mj，会提示不少关键词出来，我这个时候在想是否可以做一下，下方的点击按钮，功能是点击切换提示词，因为chat的提示词混在用画图的时候特别不适。
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38576989/f8589deb-0e19-4b3b-8e8f-56324473bc19)
2.由于在画图期间，chat的关键词干扰，导致我输入prompt，还是有一条或者几条提升跟随，正常很多人习惯回车打到输入框内，就会将和画画无关的chat提示词完全覆盖掉刚才的输入，由于是/mj，正常我们输入chat没有这个问题，是因为，我们正常问问题，很少使用”/“，因此在我们使用”/mj“，输入回车，只要有提示，就会被覆盖，给人一种不友好的感觉
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38576989/21470c0b-66a0-4296-aca5-75119e8a04fc)

**Comment by white-elephant-li** [comment]
由于next web默认发送是ctrl +enter，但是很多人聊天养成的习惯是直接回车【enter】，因此我认为应该不止我一个人会出现这个问题

**Comment by Cuauhtemoc9** [comment]
关于1
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/44720250/bf53037d-d880-4878-8439-2f36b28a3e78)

**Comment by white-elephant-li** [comment]
但是我一会画画，一会儿chat，我总要到设置那开关，不太友好把

**Comment by jasontips** [comment]
确实有这个问题，也确实烦人。。。
如果绘图指令不用/开头应该就能解决了，是不是可以考虑换个符号开头，比如#mj xxx啥的

**Comment by Licoy** [comment]
已优化
