### ISSUE TITLE
[Feature]  LaTeX support

### ISSUE THREAD

**Issue by DevFil** [Licoy/ChatGPT-Midjourney#110]
Hello Licoy,

I hope this message finds you well. I am an user of this client and greatly appreciate the work you've put into developing such a useful tool.

As someone who frequently works with mathematical notation, I've found that the ability to clearly and accurately display complex equations is essential. To that end, I believe that integrating LaTeX support would significantly enhance its functionality for myself and others in the scientific and academic communities.

Thank you for considering my request. I am looking forward to any possibility of this feature's integration in the future updates.

Best regards

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
