### ISSUE TITLE
[Bug] Cannot run /mg command. Error: model_not_found

### ISSUE THREAD

**Issue by malbruk** [Licoy/ChatGPT-Midjourney#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ X ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

Hi,
I deployed the app to Vercel and set all the env variables. When I type /mg command in input, I get this error:
`{
  "error": {
    "message": "The model `midjourney` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}`
I tried cloning the code an run locally, and still the same error.
Did I miss something?

Thanks!

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
