### ISSUE TITLE
I is asking acces code after any prompt. Where do I find it???[Feature] 

### ISSUE THREAD

**Issue by cobayashi7411** [Licoy/ChatGPT-Midjourney#114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
