### ISSUE TITLE
[Bug] 本地部署提示 Cannot find module 'stream/web'

### ISSUE THREAD

**Issue by cccisbug** [Licoy/ChatGPT-Midjourney#119]
npm install
276 packages are looking for funding
  run `npm fund` for details
(base) CelgolddeMBP:ChatGPT-Midjourney CuiGuiXiang$ npm run build
> chatgpt-midjourney@3.2.3 build
> cross-env BUILD_MODE=standalone next build

unhandledRejection Error: Cannot find module 'stream/web'
Require stack:
- /ChatGPT-Midjourney/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js

nodejs v16.0.0  MacOS

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
