### ISSUE TITLE
使用命令”/Mj"后，对话框总是强制到底

### ISSUE THREAD

**Issue by white-elephant-li** [Licoy/ChatGPT-Midjourney#12]
使用命令”/Mj"后，对话框到最下面，很合理，但是一直强制到底，无法看到上面历史记录了，我这边属于使用了"/mj"就会一直强制到对话框的最底部，无法看到上面的历史记录,即使图片生成完毕，也是一直强制到对话框最底部

**Comment by Licoy** [comment]
在图像的生成过程中，只要任务没有完成每次更新都会到最底部

**Comment by white-elephant-li** [comment]
您好，这边最新版测试反应的bug是图像生成完毕，也会到最底部

**Comment by Licoy** [comment]
图像生成完成之后，之后的消息就不会再到底部了

**Comment by white-elephant-li** [comment]
您好，这边测试过，您说的是正常情况，下图是两张图后仍然疯狂到底，由于这边猜测您的逻辑是任务结束，但是很明显失败的任务下，整个页面的刷新还是会一直在底部。准确来说，是一旦任务中断，结束，出错，加载失败，整个页面会一直加载到底部，您好，这边也不是故意找茬，只是善意的提出bug。
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38576989/45d898d3-b830-493c-8ce3-e3da053ab5d6)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38576989/56f59e5c-d3d2-4cc4-abb2-05496801088b)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38576989/09e96ce0-89df-4257-a6ef-f7cb5d111024)

**Comment by white-elephant-li** [comment]
一张图片提交任务后没有加载图片的情况也是一样会一直加载到页面底部，想往上拉看看图片的对照，就很困难

**Comment by Licoy** [comment]
只要有检测状态返回就会自动滚动到底部，除非任务结束/错误/不存在等终止状态，否则都会一直请求任务状态直至结束

**Comment by white-elephant-li** [comment]
目前这边测试下来，就是任务结束/错误/以及提交后没有照片的情况都会导致自动滚到底部，而且在5-10分钟内都是如此，如果您的网站是没有问题的，这边可以给您提供视频证明，以及下载的版本和相关环境

**Comment by white-elephant-li** [comment]
qq390023206

**Comment by Licoy** [comment]
你可以加入到QQ群内发布错误视频

**Comment by white-elephant-li** [comment]
已申请

**Comment by Cuauhtemoc9** [comment]
+1同样遇到该问题，会不断回滚到底部

**Comment by Licoy** [comment]
已优化
