### ISSUE TITLE
[Bug] 点击设置按钮报错

### ISSUE THREAD

**Issue by OriginalCobra** [Licoy/ChatGPT-Midjourney#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
![Uploading 微信截图_20240320120256.png…]()

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
