### ISSUE TITLE
输入/mj a small car 后台报错

### ISSUE THREAD

**Issue by ysh886** [Licoy/ChatGPT-Midjourney#121]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
