### ISSUE TITLE
[Bug] 输入BUG标题

### ISSUE THREAD

**Issue by tkizm1** [Licoy/ChatGPT-Midjourney#123]
**Describe the bug**

**To Reproduce**
1. 对已经生成的图片，点击v1,v2,v3,v4，reroll
2. 显示 任务已提交至Midjourney服务器，没有后续的反应

**Expected behavior**
生成新图片

**Screenshots**
<img width="883" alt="image" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/5886048/20ab6570-3996-464c-9cc4-d83ff4968cd7">

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**
 - OS: mac [e.g. iOS]
 - Browser chrome [e.g. chrome, safari]
 - Version latest [e.g. 22]

**Additional Logs**
Add any logs about the problem here.

**Comment by yaohuiwu** [comment]
Please turn off the Remix mode in your discord app:

1. Run the /settings command;
2. Click the Remix mode to close it;
