### ISSUE TITLE
第三方mj-api如何填写接口参数？

### ISSUE THREAD

**Issue by xiaos911** [Licoy/ChatGPT-Midjourney#127]
**描述问题**
我购买了第三方的mjapi，在参数设置中没有找到对应的参数说明，已知mj.api-secret: 接口密钥。但该部署中未提供改参数名称。
说明中只有【MJ_SERVER_ID】Discord 服务器ID。希望能告诉我如何添加接口秘钥参数。

**一些必要的信息**
 - 版本： [v3.2.3]
 - 部署方式：[docker]

**Comment by Licoy** [comment]
不支持第三方
