### ISSUE TITLE
[Bug] 显示绘图任务已提交至Midjourney服务器，但无法返回绘图结果，discord有生成图片

### ISSUE THREAD

**Issue by chakson** [Licoy/ChatGPT-Midjourney#130]
**Describe the bug**
显示绘图任务已提交至Midjourney服务器，但无法返回绘图结果。去discord看了，有生成图片。浏览器控制台没有报错，服务器api日志也没报错

**To Reproduce**
1. Go to 'New Chat'
2. Enter: /mj [a dog]

**Expected behavior**
可以正常返回绘图结果

**Screenshots**
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/13362753/7c35f12e-5e66-4f0b-be72-68a4e623b2eb)

**Deployment**
Unbuntu20.04 Server

**Desktop (please complete the following information):**

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
