### ISSUE TITLE
[Bug] 总是隔一段时间不能生成图像，重启之后恢复正常

### ISSUE THREAD

**Issue by yaohuiwu** [Licoy/ChatGPT-Midjourney#131]
**Describe the bug**
总是隔一段时间不能生成图像，重启之后恢复正常。已经出现很多次了。怀疑是websocket链接断开了。

**To Reproduce**

**Expected behavior**
不需要重启。

**Screenshots**

**Deployment**
- [v] Docker
- [ ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional Logs**

**Comment by yaohuiwu** [comment]
补充日志信息：
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:720:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1714:19)
    at TLSSocket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'gateway.discord.gg',
  port: 443,
  localAddress: undefined
}

出现这个错误之后就没有heartbeat日志了。

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
