### ISSUE TITLE
[Bug] 环境变量MJ_PROXY_KEY无效，midjourney优先使用OPENAI_API_KEY

### ISSUE THREAD

**Issue by Yanyutin753** [Licoy/ChatGPT-Midjourney#143]
### Describe the bug

最新版的ChatGPT-Midjourney

环境变量MJ_PROXY_KEY无效，midjourney优先使用OPENAI_API_KEY的值进行请求

希望大大修复这个问题，十分感谢！！！

**Comment by Licoy** [comment]
已合并
