### ISSUE TITLE
如何修改默认监听的端口3000？

### ISSUE THREAD

**Issue by jasontips** [Licoy/ChatGPT-Midjourney#15]
如此，我grep 3000半天没找到在哪里定义的，麻烦知道的朋友指点一下，谢谢

**Comment by Licoy** [comment]
docker 启动直接修改参数即可 -p 你想要的端口:3000

**Comment by jasontips** [comment]
感谢大佬回答，我是本地化部署的，不是用docker, 在哪改端口呢？

**Comment by Licoy** [comment]
参考：https://www.nuxtjs.cn/faq/host-port

**Comment by jasontips** [comment]
> 参考：https://www.nuxtjs.cn/faq/host-port

这项目是有的nextjs吧？不是nuxtjs。
在package.json中将next start 后加个-p 3001就可以改端口为3001了
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/130386594/c7d8dc81-94f4-456c-92a1-d255510d5eac)

**Comment by Licoy** [comment]
是的，不好意思贴错了：https://medium.com/frontendweb/how-to-change-port-in-nextjs-1b99930bb81f
