### ISSUE TITLE
[Bug] 图片反代参数MJ_DISCORD_CDN_PROXY在v3.4.1版本失效问题

### ISSUE THREAD

**Issue by tom00014** [Licoy/ChatGPT-Midjourney#156]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker部署licoy/chatgpt-midjourney:v3.4.1版本，以下是部署启动脚本
docker run -d -p 3001:3000 \
    -e OPENAI_API_KEY="sk-proj-****" \
    -e BASE_URL="https://api.openai.com" \
    -e MJ_PROXY_URL="http://xxx.1x.48.1xx:8086" \
    -e MJ_PROXY_KEY="******" \
    -e MJ_DISCORD_CDN_PROXY="https://midjourney.xxx.com" \
    --restart=always \

可以生成图片请求
画面提示: 奥特曼 --v 6 --ar 1:1
AI模型: mj
AI动作: imagine
任务ID: 1724745976911BFF
状态: 成功

无法获取图片结果，通过排查发现浏览器跳转https://cdn.discordapp.com/attachments/***/***，记得之前的版本是可以使用MJ_DISCORD_CDN_PROXY参数自定义Discord 图片代理的，请问现在如何反代图片cdn.discordapp.com域名

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
![image](https://github.com/user-attachments/assets/35608acf-4d11-41ab-9f4f-e75a3855f2a3)

**Comment by Licoy** [comment]
3.4.1版本不支持此参数，你应该在上游MJ_PROXY中处理相关图片链接，比如将它存储到OSS之类的
