### ISSUE TITLE
提交任务报错: 任务提交错误：Unexpected end of JSON input

### ISSUE THREAD

**Issue by liangxiaowucai** [Licoy/ChatGPT-Midjourney#2]
提交任务报错了，可以看看吗？
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/42310513/73362b21-cc50-41f8-ab21-a8d6dd47c37b)

**Comment by liangxiaowucai** [comment]
midjourney-proxy的docker版本的地址是：/mj/trigger/submit
docker启动之后，提交的地址是: /mj/submit/imagine

![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/42310513/3ab4efd0-9d50-4847-90f4-5a4df28b88a7)

**Comment by Licoy** [comment]
`/mj/trigger/submit`是旧版本了，新版本的都是`/mj/submit/imagine`

**Comment by liangxiaowucai** [comment]
> `/mj/trigger/submit`是旧版本了，新版本的都是`/mj/submit/imagine`

好的，我再去看看，感谢

**Comment by liangxiaowucai** [comment]
> `/mj/trigger/submit`是旧版本了，新版本的都是`/mj/submit/imagine`

已更新，目前可以显示提交任务了，不过有个问题，这个图片，您这边是直接嵌入到image的吗？如果本地不连魔法，图片打不开的吧，后期是否会有转存的开发呢？

**Comment by Licoy** [comment]
后期会有的，提供图片的proxy服务或者download到服务器，然后提供url供客户端访问

**Comment by Licoy** [comment]
图片反代可以使用[midjourney-proxy](https://github.com/novicezk/midjourney-proxy/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9)中的`mj.ng-discord.cdn`参数达到效果

**Comment by sishierdianyijiuwu** [comment]
任务提交错误：Failed to fetch

**Comment by Cuauhtemoc9** [comment]
> 后期会有的，提供图片的proxy服务或者download到服务器，然后提供url供客户端访问

期待！感谢大佬！

**Comment by FunAomi** [comment]
又碰到了这个错误,
任务提交错误：Unexpected end of JSON input，
docker log:
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/38908099/42f1ac92-5872-4152-8e4b-b1c30330c702)
但是我API接口是通的啊，我到容器里，也能ping到我host。有点奇怪。

**Comment by Licoy** [comment]
你可以在容器内 curl http://yourip:port/mj/doc.html 试试

**Comment by FunAomi** [comment]
容器的问题，新加了个网络，走内网了。
之前的环境是一个host,一个bridge。
感谢，❤️ @Licoy
