### ISSUE TITLE
[Bug] docker pull not found

### ISSUE THREAD

**Issue by mufanGuo** [Licoy/ChatGPT-Midjourney#20]
**Describe the bug**  
centos7  
docker  
docker pull not found

**To Reproduce**
1. docker pull licoy/chatgpt-midjourney:v1.3.2  

**Expected behavior**
pull success
but  
manifest for docker.io/licoy/chatgpt-midjourney:v1.3.2 not found

**Comment by Licoy** [comment]
https://hub.docker.com/r/licoy/chatgpt-midjourney/tags

please use docker official mirror

**Comment by mufanGuo** [comment]
> 
still not found
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/39327086/46f52d8c-b1e8-4a7b-b22c-049d4ff88154)

**Comment by mufanGuo** [comment]
> https://hub.docker.com/r/licoy/chatgpt-midjourney/tags
> 
> 请使用docker官方镜像
still not found
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/39327086/41ccda93-7505-4f54-a14e-67b9ae9f799b)

**Comment by Licoy** [comment]
debian 11 ，没有问题

```
root@remote:~# docker pull licoy/chatgpt-midjourney:v1.3.2
v1.3.2: Pulling from licoy/chatgpt-midjourney
8a49fdb3b6a5: Already exists 
9b5fc0e37d5d: Already exists 
8464cfe31354: Already exists 
1b41de32b0a5: Already exists 
c0b3c49fd982: Pull complete 
d0afd65d8cff: Pull complete 
85c9fb721063: Pull complete 
c345a42c1fa5: Pull complete 
12d72631d1df: Pull complete 
27a5ad581c87: Pull complete 
Digest: sha256:4a06e6094e9b4bda69eb5bbb3f367b7c0f104afab15a9188b704304f4dca22d5
Status: Downloaded newer image for licoy/chatgpt-midjourney:v1.3.2
docker.io/licoy/chatgpt-midjourney:v1.3.2
```

**Comment by mufanGuo** [comment]
> debian 11 ，没有问题
> 
> ```
> root@remote:~# docker pull licoy/chatgpt-midjourney:v1.3.2
> v1.3.2: Pulling from licoy/chatgpt-midjourney
> 8a49fdb3b6a5: Already exists 
> 9b5fc0e37d5d: Already exists 
> 8464cfe31354: Already exists 
> 1b41de32b0a5: Already exists 
> c0b3c49fd982: Pull complete 
> d0afd65d8cff: Pull complete 
> 85c9fb721063: Pull complete 
> c345a42c1fa5: Pull complete 
> 12d72631d1df: Pull complete 
> 27a5ad581c87: Pull complete 
> Digest: sha256:4a06e6094e9b4bda69eb5bbb3f367b7c0f104afab15a9188b704304f4dca22d5
> Status: Downloaded newer image for licoy/chatgpt-midjourney:v1.3.2
> docker.io/licoy/chatgpt-midjourney:v1.3.2
> ```

![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/39327086/f3438992-2157-44a1-b6fc-692e9873e628)
try agin，still not found, don't know what went wrong.   
`docker search`  be available.

**Comment by Licoy** [comment]
try `docker pull licoy/chatgpt-midjourney:v1.3.3`
