### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by m-musi** [Licoy/ChatGPT-Midjourney#21]
使用的时候报错信息
[Time]  2023/6/14 18:28:53
[Auth] admin did not provide an api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
[OpenAI]  [TypeError: RequestInit: duplex option is required when sending a body.]

**Comment by Licoy** [comment]
这个可以反馈主项目 chatgpt-next-web
