### ISSUE TITLE
请教一下avatar定义

### ISSUE THREAD

**Issue by jasontips** [Licoy/ChatGPT-Midjourney#22]
我想添加一些自定义的Mask，但是不太清楚avatar的定义，不知道怎么引用图标，有没有哪里可以查到avatar图标对应的代码？
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/130386594/f9bd1225-5873-43e7-8c2d-cd69e07187a2)
是不是有个预定义的图标库啊？知道的朋友麻烦指点一下，谢谢！

**Comment by Licoy** [comment]
这个应该是emoji的某种编码吧，后续我看看暂时没有研究
