### ISSUE TITLE
有没有可能给绘图指令加个密码保护

### ISSUE THREAD

**Issue by jasontips** [Licoy/ChatGPT-Midjourney#27]
现在页面上会对chatgpt有密码和api key来保护gpt不被滥用，但是在没有密码和api key的情况下，/mj指令还是可以正常使用的，我不想在页面上暴露mj proxy api的地址，有没有可能给/mj指令也加个保护，可以设置一个或多个密码，没密码不让用/mj指令。

**Comment by Licoy** [comment]
本身就是支持的，只要你配置了`CODE`变量，如果没有输入访问密码请求就会被拦截
