### ISSUE TITLE
[Bug] 突然用不了

### ISSUE THREAD

**Issue by KaMang06** [Licoy/ChatGPT-Midjourney#29]
前面还出图正常，现在提交一直提示FAILURE，去midjourney proxy里状态查询也是提示异常如下：
    "action": "IMAGINE",
    "id": "7564193164428700",
    "prompt": "Seascape, Coastal view, Beach sunset, Waves crashing, Sandy shores",
    "promptEn": "Seascape, Coastal view, Beach sunset, Waves crashing, Sandy shores",
    "description": "/imagine Seascape, Coastal view, Beach sunset, Waves crashing, Sandy shores",
    "state": null,
    "submitTime": 1686998127218,
    "startTime": 1686998127234,
    "finishTime": 1686998127596,
    "imageUrl": null,
    "status": "FAILURE",
    "progress": "",
    "failReason": "Invalid Form Body"

discord里的midjourney账号正常的。

**Comment by Licoy** [comment]
全部更新到最新版即可
