### ISSUE TITLE
ChatGPT-Midjourney交流群

### ISSUE THREAD

**Issue by Licoy** [Licoy/ChatGPT-Midjourney#30]
若有疑问群内小伙伴会协助您进行解决：

> ⚠️ 若下方一键加入无法使用请自行复制群号码进行搜索添加。

- QQ群号码：849273126 [一键加入群](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=gAGpNxOKdRB3L_IiHWAfT4MUQzgBOor-&authKey=Ty8WQgZFub8W1EsG3LQE2B3xxRRBzD0Rj1rPyRVFdT6IqnJgGcpPZB5l8ZVJTB1n&noverify=0&group_code=849273126)

**Comment by xiaoxiaoyaonie** [comment]
你交流群不让我进啊。能否在开几个群？

**Comment by Licoy** [comment]
为什么不让你进？提示什么

**Comment by qingfengguozhi** [comment]
怎么进群啊哥哥们· 连接打不开了都

**Comment by Licoy** [comment]
@xiaoxiaoyaonie @qingfengguozhi 已更新，若一键加入无法使用请自行复制群号码进行搜索添加。

**Comment by superw2018** [comment]
Unexpected non-whitespace character after JSON at position 75  重新装了下代理，然后就出这个问题了，也不知道哪里的错，代理那个正常的，调试可以正常返回结果的。

**Comment by qingwa007** [comment]
可以进这个群，主要这个卡好稳定 https://chatgpt007.wordpress.com/2023/07/13/chatgpt-plus-2/

**Comment by Bellet222** [comment]
I inserted my discord data into the .env.template file, but it gives me the error Task submission failed: midjourney api server start failed

**Comment by Bellet222** [comment]
I inserted my discord data into the .env.template file, but it gives me the error Task submission failed: midjourney api server start failed

**Comment by chen220518** [comment]
下载解压后，没看到安装文件，win10上怎么安装和运行？求解
