### ISSUE TITLE
[Bug] midjourney绘图用V的时候会提交但是没有后续

### ISSUE THREAD

**Issue by KaMang06** [Licoy/ChatGPT-Midjourney#32]
绘图选择V的时候会提交但是没有后续返回
**画面描述:** VARIATION::1::3525525412808094
**任务ID:** 7709611621575780
**任务状态:** [2023/6/18 16:17:44] - 任务已提交至Midjourney服务器

discord里V的按钮是绿色的 但是估计没有提交的，因为如果在discord手动点V1-4是会弹窗提示要确定的  不知道是不是midjourney-proxy那边没有做处理

**Comment by Licoy** [comment]
discord中输入/setting 关闭remix mode

**Comment by whoiskoala** [comment]
> 

关闭之后显示:
**画面描述:** pig
**任务ID:** 5711802767502446
**任务状态:** [6/30/2023, 2:53:41 AM] - 任务正在运行，当前进度：0%
进度始终为0不显示图，但discord里已经完成绘图

**Comment by vual** [comment]
同问。不知道是midjourney-proxyd代理的问题。

**Comment by whoiskoala** [comment]
> 同问。不知道是midjourney-proxyd代理的问题。

Midjourney- proxy的issue里看到是MJ 已经将  Variations by 修改为 Variations (Strong) by 导致的

**Comment by Licoy** [comment]
请更新至V3.0.x
