### ISSUE TITLE
在网页输入画图指令时，也显示图片成功画出，discord中也能看到，但无法在ChatGPT new wab中返回图片

### ISSUE THREAD

**Issue by SLHE135** [Licoy/ChatGPT-Midjourney#34]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在网页输入画图指令时，也显示图片成功画出，discord中也能看到，但无法在ChatGPT new wab中返回图片

**如何复现**
未知，Midjourney代理使用的谷歌海外服务器，

**截图**
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/86449824/592253c5-ffcc-415d-a33f-3f47b8b78c60)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/86449824/842e44cc-7ad7-4281-bf29-72bc6ed3113a)

**一些必要的信息**
 - 系统：[mac air]
 - 浏览器： [chrome,]
 - 版本： [m-p-2.2.3]
 - 部署方式：[docker]

**Comment by Licoy** [comment]
设置中勾选图片自代理

**Comment by Licoy** [comment]
在国内肯定无效呀，自代理下面的提示写的很清楚

**Comment by Licoy** [comment]
参考midjourney-proxy项目中的代理配置
