### ISSUE TITLE
midjourney-proxy 完全搞不明白求教程

### ISSUE THREAD

**Issue by xiaoxiaoyaonie** [Licoy/ChatGPT-Midjourney#35]
midjourney-proxy 能否出个搭建教程啊  包括vercel搭建 有视频教程吗。。油管毛都没收到

**Comment by Licoy** [comment]
请参考：[midjourney-proxy](https://github.com/novicezk/midjourney-proxy) 项目

**Comment by git-syl** [comment]
参考这个：
https://github.com/novicezk/midjourney-proxy/blob/main/docs/discord-bot.md

https://github.com/novicezk/midjourney-proxy/blob/main/docs/discord-params.md

**Comment by xiaoxiaoyaonie** [comment]
MIDJOURNEY_PROXY_URL

> 请参考：[midjourney-proxy](https://github.com/novicezk/midjourney-proxy)项目目标

MIDJOURNEY_PROXY_URL这 个怎么填写呢  我上面的代码都弄完了的 500错误。。。

**Comment by git-syl** [comment]
> MIDJOURNEY_PROXY_URL
> 
> > 请参考：[midjourney-proxy](https://github.com/novicezk/midjourney-proxy)项目目标
> 
> MIDJOURNEY_PROXY_URL这 个怎么填写呢 我上面的代码都弄完了的 500错误。。。
> 
> mj_discord_bot_token 环境配置这样吗？ https://discord.com/api/oauth2/authorize?client_id=xxxx&permissions=xxxx&scope=bot%20applications.commands

1）
这是两个项目，MIDJOURNEY_PROXY_URL填midjourney-proxy项目的服务器ip和端口。
你得先把midjourney-proxy项目启动成功，然后去chatgpt-midjourney项目配置填入服务器的http://ip:port
和端口都是midjourney-proxy项目的

2）肯定不对啊，你再看遍。
mj.discord.bot-token是
这个链接中https://github.com/novicezk/midjourney-proxy/blob/main/docs/discord-bot.md
步骤2、获取机器人Token里面的token

**Comment by Xscapeyy** [comment]
> > MIDJOURNEY_PROXY_URL
> > > 请参考：[midjourney-proxy](https://github.com/novicezk/midjourney-proxy)项目目标
> > 
> > 
> > MIDJOURNEY_PROXY_URL这 个怎么填写呢 我上面的代码都弄完了的 500错误。。。
> > mj_discord_bot_token 环境配置这样吗？ https://discord.com/api/oauth2/authorize?client_id=xxxx&permissions=xxxx&scope=bot%20applications.commands
> 
> 1） 这是两个项目，MIDJOURNEY_PROXY_URL填midjourney-proxy项目的服务器ip和端口。 你得先把midjourney-proxy项目启动成功，然后去chatgpt-midjourney项目配置填入服务器的http://ip:port 和端口都是midjourney-proxy项目的
> 
> 2）肯定不对啊，你再看遍。 mj.discord.bot-token是 这个链接中https://github.com/novicezk/midjourney-proxy/blob/main/docs/discord-bot.md 步骤2、获取机器人Token里面的token @xiaoxiaoyaonie

大佬，midjourney-proxy我用zeabur部署成功了，有一个链接，那我chatgpt-midjourney里MIDJOURNEY_PROXY_URL是填之前的链接吗，我现在是404的问题，
任务提交失败：
状态码：404
响应体：{"timestamp":"2023-06-22T05:43:08.484+00:00","status":404,"error":"Not Found","path":"/mj/mj/submit/imagine"}

**Comment by Licoy** [comment]
路径填错了，后面不用跟 `/mj`

**Comment by Xscapeyy** [comment]
> 路径填错了，后面不用跟 `/mj`

哇，非常感谢，解决了。
现在会显示任务已提交至Midjourney服务器，但是好久都不会返回图片，显示连接超时

**Comment by Licoy** [comment]
具体点

**Comment by quqilala** [comment]
您好！MJ的代理地址均已部署完毕，mj proxy api可正常访问，提交对话/mj ,提示：任务提交失败：
状态码：401
响应体：{"error":true,"msg":"empty access code"}

**Comment by bandusix** [comment]
地址的格式  填的就是 railyway 的 ip + port

但是显示

Task submission failed: 
Status code: 504
Response body: An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT

**Comment by Licoy** [comment]
> 您好！MJ的代理地址均已部署完毕，mj proxy api可正常访问，提交对话/mj ,提示：任务提交失败： 状态码：401 响应体：{"error":true,"msg":"empty access code"}

主要是这个问题我这边无法复现，能否提供一下复现流程

**Comment by Licoy** [comment]
> midjourney-proxy 服务部署Zeabur
> 
> ```
> PORT=8080
> mj_discord_guild_id=xxx
> mj_discord_channel_id=xxx
> mj_discord_user_token=xxx
> ```
> 
> https://**.zeabur.app/mj 能打开首页。未设置任何参数。
> 
> ChatGPT-Midjourney 前端部署Vercel `CODE=**
> 
> OPENAI_API_KEY=**
> 
> MIDJOURNEY_PROXY_URL=https://**.zeabur.app:8080
> 
> ` 访问**.vercel.app 可以chatgpt访问聊天。 不能/mj cat。 任务提交失败： 状态码：401 响应体：{"error":true,"msg":"empty access code"}

输入访问code了吗

**Comment by Licoy** [comment]
端口取消？

**Comment by michael230811** [comment]
请问楼上各位大佬，我遇到下面的问题该如何处理？
画面描述: a tiger
任务ID: 1692067317731634
任务状态: [2023/8/15 10:41:55] - 未知频道

任务提交失败：关联任务状态错误

我是MJ付费会员，频道ID也有了；但看了教程后不知道哪里去服务器ID。

URL上只有@me这种信息，谢谢。

**Comment by Licoy** [comment]
请更新至V3.0.x
