### ISSUE TITLE
[Feature] 绘画进行一半，中途退出，或者刷新页面，能否请求一下最新结果

### ISSUE THREAD

**Issue by fh12** [Licoy/ChatGPT-Midjourney#36]
**你想要什么功能或者有什么建议？**
绘画进行一半，中途退出，或者刷新页面，就在也看不到这个绘图的最终结果，作者大大，初次加载页面或刷新页面能否根据任务状态，如果是任务进行中的任务，都请求一下最新结果？

**其他信息**
图片的每一次进度，会出现一闪一闪的情况，能否实现无感的切换，或者给页面加个固定高度？

**Comment by Licoy** [comment]
后续会增加刷新重载任务支持

**Comment by Licoy** [comment]
v1.3.7已支持
