### ISSUE TITLE
[Feature] 异步获取绘画结果，增加灵犀Midjourney-API支持

### ISSUE THREAD

**Issue by lym0302** [Licoy/ChatGPT-Midjourney#37]
**这个功能与现有的问题有关吗？**
这篇文档:  https://docs.qq.com/doc/DYnN4dXNDTk5UekRW   给出了免部署Midjourney-api接口，只需要MJ 的token就能生成api，并给出了利用生成的API部署本项目的命令（无需部署除本项目之外的其他项目）：

docker run -d -p 3000:3000  \
  -e OPENAI_API_KEY="sk-xxxxxxxxx" \
  -e BASE_URL="http://ai.4387.top:8010" \
  -e MIDJOURNEY_PROXY_URL="http://ai.4387.top:8609" \
  -e  MIDJOURNEY_PROXY_API_SECRET="sk-xxxxxxxx"  \
   licoy/chatgpt-midjourney:v1.3.1

**你想要什么功能或者有什么建议？**
建议增加异步获取绘画结果，参考API接口文档：https://docs.qq.com/doc/DYmpqVVR3U3JnaVho

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Samge0** [comment]
这哥们提供的链接"http://ai.4387.top:8609/"被google浏览器提示有诈骗风险。

大家不要轻易使用别人提供的代理链接，
同时也不要在不明网站查询key的余额，
否则容易被盗用。

![安全错误](https://github.com/Licoy/ChatGPT-Midjourney/assets/17336101/d08436ef-1bd6-49e1-be64-acc58a5dd2d1)
