### ISSUE TITLE
页面能否支持设置API Base URL？

### ISSUE THREAD

**Issue by jasontips** [Licoy/ChatGPT-Midjourney#41]
chatgpt-next-web是支持的，能否合一下这个功能？比较方便部署在国内使用API proxy的。
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/130386594/f159b932-33df-442b-b8b1-768846cef24a)

**Comment by befantasy** [comment]
是啊，这个功能chatgpt-next-web是有的，也很有必要。

**Comment by Licoy** [comment]
请更新至V3.0.x
