### ISSUE TITLE
Zeabur部署项目后，手机端不能使用

### ISSUE THREAD

**Issue by Xscapeyy** [Licoy/ChatGPT-Midjourney#46]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
Zeabur部署项目后，手机端不能使用,电脑端能正常使用。手机端访问会出现

```json
{
  "error": true,
  "message": "Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point."
}
```

**如何复现**
请告诉我们你是通过什么操作触发的该问题。
手机端登录就出现这个问题

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![Screenshot_2023-06-23-18-22-25-42_df198e732186825c8df26e3c5a10d7cd](https://github.com/Licoy/ChatGPT-Midjourney/assets/103979275/e4b2302e-a858-4d00-8a4d-b6fdef79edcc)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16] 手机端
 - 浏览器： [比如 chrome, safari] Edge浏览器
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]Zeabur

**Comment by Licoy** [comment]
安卓版本多少？用的什么浏览器？

**Comment by Xscapeyy** [comment]
> 

安卓版本13，浏览器是Edge浏览器

**Comment by Xscapeyy** [comment]
> > 
> 
> 安卓版本13，浏览器是Edge浏览器

我浏览器更新了下就解决了
