### ISSUE TITLE
[Bug] 更新后提示这个

### ISSUE THREAD

**Issue by KaMang06** [Licoy/ChatGPT-Midjourney#48]
/mj prompt提交后秒提示下面错误
任务提交失败：
状态码：401
响应体：{"error":true,"msg":"empty access code"}
（ChatGPT-Midjourney最新版本0625）

Midjourney-proxy（最新版本2.3.2）没有收到任何提交过来的信息。
Discord账号正常 获取的token也是正常的（在另一个服务测试正常使用）

**Comment by quqilala** [comment]
您好，我也遇到了同样的问题。

**Comment by llwc594** [comment]
111

**Comment by China-Deng** [comment]
docker 生成项目的时候去掉CODE 虽然暂时不知道是干嘛用的

**Comment by vual** [comment]
你这是midjourney-proxy那边设置了api-secret，你要在项目里填 对应值 MIDJOURNEY_PROXY_API_SECRET=

**Comment by Licoy** [comment]
请更新至V3.0.x
