### ISSUE TITLE
[Bug] 等待回复时，聊天记录错位，且发送一个指令，会有两个回复显示正在输入，等完成就变一个

### ISSUE THREAD

**Issue by vual** [Licoy/ChatGPT-Midjourney#49]
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/25891219/8b2c0658-5ecf-4b68-bc52-8eff1e1716f3)

**Comment by vual** [comment]
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/25891219/73e52df5-f23f-4511-8777-be0f3f8c5670)

**Comment by Licoy** [comment]
chatgpt-next-web原版也会出现此类问题，待官方更新即可
