### ISSUE TITLE
关于MIDJOURNEY_PROXY_URL

### ISSUE THREAD

**Issue by collinsman** [Licoy/ChatGPT-Midjourney#52]
docker布署，如果宿主机处于可以直接访问openai的环境（比如国内全局代理的虚拟机、海外vps），MIDJOURNEY_PROXY_URL可以填写宿主机ip（避免封号风险，避开香港节点vps/代理——此风险未确认，但香港不在openai使用地区）；如果宿主机开启代理访问openai（PROXY_URL部分填写了代理），那么MIDJOURNEY_PROXY_URL要填写公网ip（docker映射出公网）。

**Comment by Licoy** [comment]
MIDJOURNEY_PROXY_URL是你的服务器可以访问这个地址，不需要用户客户端可以访问

**Comment by collinsman** [comment]
> MIDJOURNEY_PROXY_URL是你的服务器可以访问这个地址，不需要用户客户端可以访问

同一个代理（韩国节点socks5填的ip），MIDJOURNEY_PROXY_URL填宿主机地址，报500错误，如图：
![111](https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/9ecf5406-cdc3-480f-8e4a-65cc96eece2c)
MIDJOURNEY_PROXY_URL填docker的公网地址，能正常用，如图：
![222](https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/e801e863-de9e-47ad-b285-17b51fa26d26)

**Comment by Licoy** [comment]
请更新至V3.0.x
