### ISSUE TITLE
https://cdn.discordapp.com 这个地址无法访问，大家怎么解决的？

### ISSUE THREAD

**Issue by vual** [Licoy/ChatGPT-Midjourney#54]
本身就是因为无法访问mj，所以用了mj代理。
https://cdn.discordapp.com 这个无法访问，导致任务完成了，但图片获取不到。

**Comment by CYBYOB** [comment]
@vual 上传国内cdn
<img width="1262" alt="推广-1" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/32217093/cdfae98b-e804-4242-8fc3-7b912c958058">

**Comment by Licoy** [comment]
开启自代理即可，设置里面有

**Comment by vual** [comment]
> 开启自代理即可，设置里面有

项目部署在本地，没有部署在vercel， 本地访问不了https://cdn.discordapp.com/

**Comment by vual** [comment]
> @vual 上传国内cdn <img alt="推广-1" width="1262" src="https://user-images.githubusercontent.com/32217093/249986448-cdfae98b-e804-4242-8fc3-7b912c958058.png">


> @vual 上传国内cdn <img alt="推广-1" width="1262" src="https://user-images.githubusercontent.com/32217093/249986448-cdfae98b-e804-4242-8fc3-7b912c958058.png">

有没有详细教程？

**Comment by dw3143** [comment]
海外服务器部署的
设置中关闭图像代理，本地科学上网可以成功返回图片
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/88608061/571ce126-ac16-41ff-bee2-1ee43876abd6)
设置中打开图像代理，通过自代理无法返回图片
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/88608061/7056fcbf-d9fa-42ea-abc3-a4941f73a2f2)
为什么海外服务器无法通过自代理使用，求大佬解答！

**Comment by dw3143** [comment]
> 

修好了，在midjourney-proxy中加入一个https://cdn.discordapp.com的反代变量

**Comment by Licoy** [comment]
请更新至V3.0.x

**Comment by Graypango** [comment]
> > 
> 
> 修好了，在midjourney-proxy中加入一个[https://cdn.discordapp.com的反代变量](https://cdn.discordapp.com%E7%9A%84%E5%8F%8D%E4%BB%A3%E5%8F%98%E9%87%8F)

这个怎么做？

**Comment by lei195827** [comment]
> > > 
> > 
> > 
> > 修好了，在midjourney-proxy中加入一个[https://cdn.discordapp.com的反代变量](https://cdn.discordapp.com%E7%9A%84%E5%8F%8D%E4%BB%A3%E5%8F%98%E9%87%8F)
> 
> 这个怎么做？

老哥你现在整明白了吗？我用cf反代的地址返回的是：This content is no longer available.

**Comment by Licoy** [comment]
> > > > 
> > > 
> > > 
> > > 修好了，在midjourney-proxy中加入一个[https://cdn.discordapp.com的反代变量](https://cdn.discordapp.com%E7%9A%84%E5%8F%8D%E4%BB%A3%E5%8F%98%E9%87%8F)
> > 
> > 
> > 这个怎么做？
> 
> 老哥你现在整明白了吗？我用cf反代的地址返回的是：This content is no longer available.

cloudflare不可以代理discord的域名，因为官方对此进行了限制了

**Comment by lei195827** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 修好了，在midjourney-proxy中加入一个[https://cdn.discordapp.com的反代变量](https://cdn.discordapp.com%E7%9A%84%E5%8F%8D%E4%BB%A3%E5%8F%98%E9%87%8F)
> > > 
> > > 
> > > 这个怎么做？
> > 
> > 
> > 老哥你现在整明白了吗？我用cf反代的地址返回的是：This content is no longer available.
> 
> cloudflare不可以代理discord的域名，因为官方对此进行了限制了

明白了谢谢

**Comment by zhaoxinhua** [comment]
> 开启自代理即可，设置里面有

你好，

> > > > > > 
> > > > > 
> > > > > 
> > > > > 修好了，在midjourney-proxy中加入一个[https://cdn.discordapp.com的反代变量](https://cdn.discordapp.com%E7%9A%84%E5%8F%8D%E4%BB%A3%E5%8F%98%E9%87%8F)
> > > > 
> > > > 
> > > > 这个怎么做？
> > > 
> > > 
> > > 老哥你现在整明白了吗？我用cf反代的地址返回的是：This content is no longer available.
> > 
> > 
> > cloudflare不可以代理discord的域名，因为官方对此进行了限制了
> 
> 明白了谢谢
老哥你是怎么解决的啊
