### ISSUE TITLE
[Bug] Vercel部署的会任务提交失败：Failed to fetch，Zeabru部署的就可以正常提交任务出图

### ISSUE THREAD

**Issue by Cyrus-Reed** [Licoy/ChatGPT-Midjourney#55]
Vercel部署的会任务提交失败：Failed to fetch
Zeabru部署的就可以正常提交任务出图
Vercel已添加自定义域名
环境变量都是一样的，为什么会出现这种情况呢

**Comment by Shirlman** [comment]
同问

**Comment by befantasy** [comment]
https://vercel.com/guides/how-to-enable-cors

**Comment by Licoy** [comment]
请更新至V3.0.x
