### ISSUE TITLE
[Bug] TypeError: RequestInit: duplex option is required when sending a body.  这是什么问题

### ISSUE THREAD

**Issue by llv5** [Licoy/ChatGPT-Midjourney#56]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
在最新版的的代码中，我下的是1.3.9版本， 部署到服务器中后，问答报这个错误。
TypeError: RequestInit: duplex option is required when sending a body.
但是在本地运行的就可以正常问答，这是为什么

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/16055914/54e91595-d753-48b7-8a9f-e2e35d62890b)
**一些必要的信息**
 - 系统：linux  debain
 - 浏览器：chrome
 - 版本：1.3.9
 - 部署方式：服务器部署

**Comment by Licoy** [comment]
请更新至V3.0.x
