### ISSUE TITLE
can not load img in dev evelopment

### ISSUE THREAD

**Issue by xiaosunJessica** [Licoy/ChatGPT-Midjourney#58]
<img width="1229" alt="image" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/17615820/dd9fee16-1c1c-4e7d-bc97-a2cbeec204ea">

npm run dev

when I use MidJourney function, I can not load image

**Comment by Licoy** [comment]
Check if your local network can access cdn.discordapp.com

**Comment by Licoy** [comment]
请更新至V3.0.x
