### ISSUE TITLE
关于 http://ip:port 怎么获取的问题，比较笨，希望好心人解答一下。

### ISSUE THREAD

**Issue by JackieIris** [Licoy/ChatGPT-Midjourney#59]
问一个比较蠢的问题，midjourney-proxy部署启动成功了。在哪里可以找到这个这个服务器的http://ip:port 啊，我打开xxx.zeabur.app/mj/后就是接口文档说明啦。哪里可以找到ip和端口填到midjourney-proxy 里呀，小白完全搞不懂呀，好气气呀。
![1](https://github.com/Licoy/ChatGPT-Midjourney/assets/25077102/b1bb311a-00ca-4bb1-9c76-a303c80024db)
![2](https://github.com/Licoy/ChatGPT-Midjourney/assets/25077102/45efa8e9-c8d3-4ab1-8417-daf2c2f349e1)
求好心人解答！！！

**Comment by Licoy** [comment]
既然xxx.zeabur.app/mj/doc.html可以访问，那么midjourney proxy url就直接填写http://xxx.zeabur.app即可

**Comment by JackieIris** [comment]
太感谢了，好人一生平安。我填写的是https://xxx.zeabur.app成功啦（小纠正一下哈）
还有一个问题就是关于secret，这个是不是要在这个项目添加MIDJOURNEY_PROXY_API_SECRET变量和在[midjourney-proxy]这个项目里添加mj_api_secret变量，并设置相同的密码，不需要前端界面上输密码是吧，我看木有地方输密码。但我这样操作还是报401错误，redeploy几次都不行，我只能删了这个变量才能用。
最后再次感谢大神的这个项目，放一张成功的图，嘻嘻。
<img width="1177" alt="image" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/25077102/9dd9b528-41e8-4cb5-93e9-2192a33d20de">
