### ISSUE TITLE
Midjourney使用Bug：Failed to fetch、Load failed

### ISSUE THREAD

**Issue by zui-lang** [Licoy/ChatGPT-Midjourney#60]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用`Vercel`部署`ChatGPT-Midjourney`前端，使用境外VPS部署`midjourney-proxy`使用正常，但使用`zeabur`部署`midjourney-proxy`时在Windows11Edge浏览器中提示`Failed to fetch`，在iOS15.6的Safari浏览器中提示`任务提交失败：Load failed`但查看discord频道发现`midjourney-proxy`运行正常

**如何复现**
使用`/mj`百分百出现
**截图**
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/77880495/7d79c642-6746-47ce-8c95-8b6fbf8f4e6b)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/77880495/b0b9e000-efca-46d9-847d-ee5c79ef0bcf)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/77880495/58957470-19ec-4a48-aebc-df8e690a0121)

**一些必要的信息**
 - 系统：windows 11、ios 15
 - 浏览器： Edge、Safari
 - 版本：20230704
 - 部署方式：vercel

**Comment by calbert2023** [comment]
chrome和360的浏览器也是这样，我感觉应该是zeabur的问题

**Comment by calbert2023** [comment]
刚刚我用zeabur部署这个程序解决了这个问题

**Comment by zui-lang** [comment]
> 刚刚我用zeabur部署这个程序解决了这个问题

是用`zeabur`部署`ChatGPT-Midjourney`前端吗

**Comment by calbert2023** [comment]
> > 刚刚我用zeabur部署这个程序解决了这个问题
> 
> 是用`zeabur`部署`ChatGPT-Midjourney`前端吗

是的

**Comment by zui-lang** [comment]
> > > 刚刚我用zeabur部署这个程序解决了这个问题
> > 
> > 
> > 是用`zeabur`部署`ChatGPT-Midjourney`前端吗
> 
> 是的

你在使用zeabur部署midjourney-proxy、vercel部署ChatGPT-Midjourney时也遇到了相同的问题吗，顺便问一下，zeabur的免费额度是怎么计算的，我怕用超了

**Comment by SagamiYun** [comment]
@zui-lang 你的方法有效，我在想是因为什么导致的是因为midjourney-proxy部署在zeabur的问题吗？如果是的话，那是不是我只要midjourney-proxy不用部署到zeabur，就解决这些问题了

**Comment by zui-lang** [comment]
> @zui-lang 你的方法有效，我在想是因为什么导致的是因为midjourney-proxy部署在zeabur的问题吗？如果是的话，那是不是我只要midjourney-proxy不用部署到zeabur，就解决这些问题了

实测在zeabur中部署midjourney-proxy和ChatGPT-Midjourney可以正常使用

**Comment by calbert2023** [comment]
> > > > 刚刚我用zeabur部署这个程序解决了这个问题
> > > 
> > > 
> > > 是用`zeabur`部署`ChatGPT-Midjourney`前端吗
> > 
> > 
> > 是的
> 
> 你在使用zeabur部署midjourney-proxy、vercel部署ChatGPT-Midjourney时也遇到了相同的问题吗，顺便问一下，zeabur的免费额度是怎么计算的，我怕用超了

是的 也遇到了 zeabur的免费额度我也不是很清楚 我也感觉用多了会超

**Comment by cooperrfeng** [comment]
> > @zui-lang 你的方法有效，我在想是因为什么导致的是因为midjourney-proxy部署在zeabur的问题吗？如果是的话，那是不是我只要midjourney-proxy不用部署到zeabur，就解决这些问题了
> 
> 实测在zeabur中部署midjourney-proxy和ChatGPT-Midjourney可以正常使用

请教下，我也是在zeabur里部署了midjourney-proxy和ChatGPT-Midjourney，
midjourney-proxy已经部署running，浏览器里 xxx.zeabur.app/mj/doc.html#/home 可以正常访问，
但是ChatGPT-Midjourney部署好后，可以前端访问，但 /mj 的话，总是 fetch failed 是什么原因呢

<img width="798" alt="企业微信截图_511a79d1-1ac0-4244-852a-97b0f46deef8" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/63777219/dd711176-c446-40da-b3dd-15652e3f979a">

**Comment by zui-lang** [comment]
> > > @zui-lang 你的方法有效，我在想是因为什么导致的是因为midjourney-proxy部署在zeabur的问题吗？如果是的话，那是不是我只要midjourney-proxy不用部署到zeabur，就解决这些问题了
> 
> > 
> 
> > 实测在zeabur中部署midjourney-proxy和ChatGPT-Midjourney可以正常使用
> 
> 
> 
> 请教下，我也是在zeabur里部署了midjourney-proxy和ChatGPT-Midjourney，
> 
> midjourney-proxy已经部署running，浏览器里 xxx.zeabur.app/mj/doc.html#/home 可以正常访问，
> 
> 但是ChatGPT-Midjourney部署好后，可以前端访问，但 /mj 的话，总是 fetch failed 是什么原因呢
> 
> 
> 
> <img width="798" alt="企业微信截图_511a79d1-1ac0-4244-852a-97b0f46deef8" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/63777219/dd711176-c446-40da-b3dd-15652e3f979a">
> 
> 

大概率是你设置的问题，如果是是共享账号，检查一下账号还能否使用，快速时长是否用完，尝试切换到relaxed模式。再看看频道号什么的

**Comment by befantasy** [comment]
应该是HTTPS跨域调用的问题。mj proxy用了https吧？换成http应该能解决。
但是希望本项目能解决以下这个问题。

**Comment by befantasy** [comment]
https://vercel.com/guides/how-to-enable-cors

**Comment by Licoy** [comment]
请更新至V3.0.x
