### ISSUE TITLE
Zeabur部署使用MJ图片加载不出来

### ISSUE THREAD

**Issue by JackieIris** [Licoy/ChatGPT-Midjourney#62]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
1.我是使用Zeabur部署的，fork的本项目和Midjourney-proxy项目，已同步，今天使用的时候图加载不出来，点击图片报错1101；
2.有时候提交任务后显示：任务已提交至Midjourney服务器，其实discord里已经执行完了，然后就任务超时了，不显示图片。
**如何复现**
问题1、2复现：使用Zeabur部署，使用/mj 命令作图
**截图**

![83f6d963abcbb3742e1c447961bc94b3](https://github.com/Licoy/ChatGPT-Midjourney/assets/25077102/bbfa54c4-a79c-40e8-83f8-74e4e0287855)

**一些必要的信息**
 - 系统：macos 13.4
 - 浏览器： chrome
 - 版本：114.0.5735.198
 - 部署方式：Zeabur

**Comment by AprilTong** [comment]
大佬 请问怎么解决的

**Comment by JackieIris** [comment]
> 大佬 请问怎么解决的

我不是大佬，参数里要有PORT=8080, 不然Zeabur就会出现图片错误。也可以自己进行反代设置（最好是美区的服务器）。
按照教程midjourney-proxy项目教程设置就可以，首先保证那个项目运行没有，然后再配置这个项目一般就没有问题。
我主要用railway，zeabur很少用了。
