### ISSUE TITLE
较长的midjourney prompt无法执行

### ISSUE THREAD

**Issue by limfoo** [Licoy/ChatGPT-Midjourney#72]
**描述问题**
较长的midjourney prompt无法执行，提示：任务提交失败：未知的任务类型

**如何复现**
比如这个prompt：
/mj Seeing a bloom under white light, Flowing transparent fabric, sleek glass thickness, transparent, pink and white and blue holographic, in the style of precise hyperrealism, mesmerizing colorscapes, i can't believe how beautiful this is, zen buddhism influence, luminous color palette, fanciful, dreamlike imagery ::3 Stockphoto, datamoshing, analytical art, urban energy, contained chaos, low bitrate high - key lighting, abstraction - création kodak elite chrome extra color, juxtaposition of light and shadow, clear colors smooth, modern minimalist, 3d render, unreal engine 5, industrial design, studio lighting, zoomed shoot, isometric, blender ::1 --ar 3:2

**截图**
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/34062417/b98e95d9-5a49-48fb-aed7-4c17ba8b8102)

**Comment by Licoy** [comment]
请更新至V3.0.x
