### ISSUE TITLE
[Bug] 请问哪里获取付费Midjourney的服务器ID？谢谢。

### ISSUE THREAD

**Issue by michael230811** [Licoy/ChatGPT-Midjourney#74]
请问楼上各位大佬，我遇到下面的问题该如何处理？
画面描述: a tiger
任务ID: 1692067317731634
任务状态: [2023/8/15 10:41:55] - 未知频道

任务提交失败：关联任务状态错误

我是MJ付费会员，频道ID也有了；但看了教程后不知道哪里去服务器ID。

URL上只有@me这种信息，例如：

https://discord.com/channels/@me/107415488680*****94

https://cdn.discordapp.com/attachments/107415488680*****94/1139373882772553758/concordance6_a_slim_and_pretty_woman_on_the_beach_in_her_bikini_7bdb6f12-dea2-47f7-a388-69f6a82843e4.png
https://cdn.discordapp.com/attachments/107415488680*****94/1134049235961122937/concordance6_a_baby_monk_wearing_an_asian_robe_in_front_of_a_wa_8c16c671-006b-4c30-95c6-c77228ceea82.png
https://cdn.discordapp.com/attachments/107415488680*****94/1118673420243189760/concordance6_captain_commandos_mack_in_Pixar_style_3fd784c1-0e87-436c-a8f9-fd57cf7a72af.png

还望各位老大指点迷津，谢谢谢谢。

**Comment by befantasy** [comment]
107415488680*****94
这个就是。
