### ISSUE TITLE
v2.0.0添加代理后不能正常启动（docker布署）

### ISSUE THREAD

**Issue by collinsman** [Licoy/ChatGPT-Midjourney#76]
1、无代理的情况，可以正常使用，日志：
<img width="522" alt="无代理" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/3a09423d-c77f-421a-91b8-5cd8c469ae6a">
2、开启代理后，不能正常使用，日志：
<img width="528" alt="开代理" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/9b88099a-6b43-4c96-a100-290f797747da">

**Comment by collinsman** [comment]
v2.0.0提交图片任务，可以正常提交生成，但不能正常返回图片（v1.3.9）正常

**Comment by Licoy** [comment]
不能正常返回图片 还是图片加载失败？

**Comment by collinsman** [comment]
> 不能正常返回图片 还是图片加载失败？

对是加载失败，百分比进度能看到，图片不能正常加载，查询任务正常
<img width="206" alt="加载失败" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/fd630dcd-0d6f-4457-920e-5ce3f3814ee9">
点击图片链接提示{"error":true,"msg":"empty access code"}

**Comment by Licoy** [comment]
ok 我晚点看看

**Comment by collinsman** [comment]
> ok 我晚点看看

图片加载失败的问题搞定了， 开启代理不能正常开启，这要怎么搞？

**Comment by Licoy** [comment]
什么代理

**Comment by collinsman** [comment]
> 什么代理

在docker里面PROXY_URL加了代理后，docker不能正常开启：
<img width="482" alt="开启代理" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/125b47be-7ddf-41d8-8e76-e580a3585542">
如果不加代理就能正常启动
<img width="492" alt="关闭代理" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/6836922a-ac77-485a-9b24-358265691856">

**Comment by Licoy** [comment]
提示的很明显，你的代理无法连接

**Comment by collinsman** [comment]
> 提示的很明显，你的代理无法连接

排查代理正常
<img width="488" alt="host" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/4d67d9f2-b018-4a38-9f45-816d6121ee32">

两台不同的vps，不开启代理，可正常运行：
<img width="664" alt="无代理ip" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/92b3b04b-6a9c-445f-b22c-88bc0b7267de">

开启代理，不能正常运行：
<img width="664" alt="无代理ip" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/50550677/ce231cdf-8821-4bf5-9cba-f644978ab625">
麻烦帮忙排查故障出在哪里，谢谢

**Comment by Licoy** [comment]
代理问题非本程序范畴，请自行处理

**Comment by AprilTong** [comment]
> > ok 我晚点看看
> 
> 图片加载失败的问题搞定了， 开启代理不能正常开启，这要怎么搞？

大佬 图片加载失败的问题怎么解决的 求赐教

**Comment by collinsman** [comment]
> > > ok 我晚点看看
> > 
> > 
> > 图片加载失败的问题搞定了， 开启代理不能正常开启，这要怎么搞？
> 
> 大佬 图片加载失败的问题怎么解决的 求赐教

升到2.0图片加载失败，更新了2.1就好了，如果还失败可以在mj-proxy添加代理，如- mj.proxy.host=10.0.0.1  - mj.proxy.port=1080，http代理

**Comment by atmgla** [comment]
> > 提示的很明显，你的代理无法连接
> 
> 排查代理正常 <img alt="host" width="488" src="https://user-images.githubusercontent.com/50550677/263604641-4d67d9f2-b018-4a38-9f45-816d6121ee32.png">
> 
> 两台不同的vps，不开启代理，可正常运行： <img alt="无代理ip" width="664" src="https://user-images.githubusercontent.com/50550677/263608192-92b3b04b-6a9c-445f-b22c-88bc0b7267de.png">
> 
> 开启代理，不能正常运行： <img alt="有代理ip" width="722" src="https://user-images.githubusercontent.com/50550677/263608478-8239730b-042f-4d0d-a3cc-76da98f8c909.png"> 麻烦帮忙排查故障出在哪里，谢谢

+1，同样的代理在netweb项目可以正常跑，来这个就不行了

**Comment by Licoy** [comment]
使用3.x，2.x的问题均不在处理

**Comment by atmgla** [comment]
> 使用3.x，2.x的问题均不在处理

我刚刚用的是最新的，3.0.24的

**Comment by xiazhibin** [comment]
v3.2.3 问题依然存在
docker部署如果使用PROXY_URL就只会监听127.0.0.1
不带PROXY_URL就可以监听0.0.0.0
