### ISSUE TITLE
[Bug]问下修改什么环境能够默认关闭midjourney图像代理，我默认开启会报如下错误： {"error":true,"msg":"empty access code"}

### ISSUE THREAD

**Issue by flashszn** [Licoy/ChatGPT-Midjourney#77]
**Describe the bug**
问下修改什么环境能够默认关闭midjourney图像代理，我默认开启会报如下错误：
{"error":true,"msg":"empty access code"}
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/105858279/6c525722-b715-4bb5-a4b6-e503ad8f5675)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Licoy** [comment]
当你身处可以直接访问 cdn.discordapp.com的环境

**Comment by Licoy** [comment]
请更新至V3.0.x
