### ISSUE TITLE
[Bug] 聊天页面问过一次问题，然后点击浏览器刷新按钮后，之前回复的答案显示出错误消息

### ISSUE THREAD

**Issue by felixchen888888** [Licoy/ChatGPT-Midjourney#78]
**Describe the bug**
聊天页面问过一次问题，然后点击浏览器刷新按钮后，之前回复的答案显示成出错误消息
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/139366455/a8be1f91-f690-4a5b-9fc5-4abab4d420f3)

**Comment by felixchen888888** [comment]
如果在zustand里面打上断点，刷新页面就正常，怀疑是异步加载的问题，但不知道怎么解决
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/139366455/c0b02648-5878-4cf0-bf37-ae7c3729c5dd)

**Comment by Licoy** [comment]
请使用 v3.x
