### ISSUE TITLE
[Feature]  i18n support?

### ISSUE THREAD

**Issue by johnfelipe** [Licoy/ChatGPT-Midjourney#82]
I want to contribute with translation to Spanish and Italian.

**Comment by Licoy** [comment]
is supported, see: 

https://github.com/Licoy/ChatGPT-Midjourney/blob/d9a1594e26b31f5c3ec2a0d45845d252c844767f/app/locales/cn.ts#L20-L57

**Comment by johnfelipe** [comment]
But is possible have Json file with strings for translate to Spanish an Italian?

**Comment by Licoy** [comment]
see: https://github.com/Licoy/ChatGPT-Midjourney/blob/d9a1594e26b31f5c3ec2a0d45845d252c844767f/app/locales/it.ts

**Comment by johnfelipe** [comment]
How update translation files with default to es and it?

**Comment by Licoy** [comment]
The default is based on the language of your system
