### ISSUE TITLE
[Bug] 显示绘图任务已提交至Midjourney服务器，但无法返回绘图结果

### ISSUE THREAD

**Issue by renhai-lab** [Licoy/ChatGPT-Midjourney#88]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Licoy/ChatGPT-Midjourney/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Licoy/ChatGPT-Midjourney/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
显示绘图任务已提交至Midjourney服务器，但无法返回绘图结果，控制台无报错日志，discord频道中无记录。
已关闭remix mode

**如何复现**
webui输入：`/mj Ariel view for a music stage design by snohetta and zaha hadid, wood and tensile tent structure in middle of urban park in san Francisco, during the day light as found in Architecture's illustrated Magazine`

**截图**
_WEB中的信息：_
```
**画面描述:** Ariel view for a music stage design by snohetta and zaha hadid, wood and tensile tent structure in middle of urban park in san Francisco, during the day light as found in Architecture's illustrated Magazine
**任务ID:** 38a2638e-f773-48f9-990a-60ef3ecac3ad
**任务状态:** [2023/9/18 11:13:22] - 任务已提交至Midjourney服务器
```

_VERCEl控制台中的信息：_
- 提交任务：

![提交任务](https://github.com/Licoy/ChatGPT-Midjourney/assets/130763230/d8f5254f-85bd-4e10-a177-21fe5a6fb085)

- 获取状态：
![获取状态](https://github.com/Licoy/ChatGPT-Midjourney/assets/130763230/db4c250b-91cc-4ee7-b358-3074a2b51a8c)

**一些必要的信息**
 - 系统：macos
 - 版本： v3.0.24
 - 部署方式：vercel

**Comment by Licoy** [comment]
“但无法返回绘图结果” 是如何判断 有提示什么

**Comment by renhai-lab** [comment]
在WEBUI中，任务状态中的时间在刷新，状态一直是'已提交至Midjourney服务器'，几十分钟都是已提交状态：

**画面描述:** Ariel view for a music stage design by snohetta and zaha hadid, wood and tensile tent structure in middle of urban park in san Francisco, during the day light as found in Architecture's illustrated Magazine
**任务ID:** 38a2638e-f773-48f9-990a-60ef3ecac3ad
**任务状态:** [2023/9/18 11:13:22] - 任务已提交至Midjourney服务器



另外，vercel控制台无报错

**Comment by renhai-lab** [comment]
好像第一次发送 /mj 命令会出现 405 错误码，第二次则一直是任务已提交状态
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/130763230/e6e28be9-30d7-4f50-8306-b3a66de8b548)

**Comment by Licoy** [comment]
在这里提交之后，查看discord里面有没有记录，如果没有则检测账号状态是否正常

**Comment by renhai-lab** [comment]
discord没有记录

**Comment by Licoy** [comment]
那就检查自己的账号可用性
