### ISSUE TITLE
[Bug] 部署最新的 3.0.24, 结果只能提示 Task has been submitted to Midjourney server， 不出图

### ISSUE THREAD

**Issue by qiulang** [Licoy/ChatGPT-Midjourney#89]
**Describe the bug**
部署最新的 3.0.24, 结果只能提示 Task has been submitted to Midjourney server， 不出图。参见下面截图

<img width="891" alt="3.0.24 problem" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/516243/bdbb0a14-e333-4d87-955f-378d15181af6">

第一次发会先显示405的错误，再发一次就是显示 Task has been submitted to Midjourney server 但是始终不出图。

用上一个版本，就是需要midjourney-proxy 重新部署一遍，可以画图。

**To Reproduce**
部署在 vercel 配置了mj相关的三个环境变量 MJ_SERVER_ID  MJ_CHANNEL_ID  MJ_USER_TOKEN

**Expected behavior**
能正常出图

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  macOS
 - Browser [e.g. chrome, safari]  chrome/safari
 - Version [e.g. 22] 3.0.24

**Comment by Licoy** [comment]
试试不用Vercel，用Docker呢

**Comment by Licoy** [comment]
另外看看你的discord频道里面有没有你对应的消息

**Comment by Licoy** [comment]
和#88的问题一致

**Comment by qiulang** [comment]
discord频道里面没有对应消息。但是我用带 proxy的版本重新部署一份新的应用是可以的

**Comment by Licoy** [comment]
> discord频道里面没有对应消息。但是我用带 proxy的版本重新部署一份新的应用是可以的。我的mj账号没问题，是每月30美金的付费账号。

试试Docker版本呢

**Comment by Licoy** [comment]
V3.1.0版本已修复

**Comment by qiulang** [comment]
我刚部署了 3.1 还是不行啊 提示  任务提交失败：Failed to fetch

**Comment by qiulang** [comment]
确实，我重新部署可以！ 

我看到代码改动就是 加了验证 `const authResult = auth(req);` 是吧 👍

```
    const authResult = auth(req);
    if (authResult.error) {
        return NextResponse.json(authResult, {
            status: 401,
        });
    }
```

**Comment by Licoy** [comment]
不是，这是另外一个优化

**Comment by qiulang** [comment]
o 参看了提交记录，这是是修改 #90 不输入密码，那 居然是去掉 `export const POST = handle;` 这个改动啊， 我不懂next.js  真没想到啊

**Comment by wwlmm** [comment]
我最新版本 docker部署 一会能出图 一会不能出图 完全处于崩溃边缘
