### ISSUE TITLE
midjourney-proxy 服务部署  这个好难部署

### ISSUE THREAD

**Issue by pdbeta** [Licoy/ChatGPT-Midjourney#9]
一直失败，建议楼主做个集成的服务，更简单的

**Comment by Licoy** [comment]
后续会考虑直接集成

**Comment by tuliwen** [comment]
> 一直失败，建议楼主做个集成的服务，更简单的
那个库作者给了 railway 一键部署了

**Comment by tuliwen** [comment]
> 一直失败，建议楼主做个集成的服务，更简单的

那个库作者给了railway一键部署了

**Comment by tuliwen** [comment]
好像还有个基于nodejs的proxy代理项目，应该能整个vercel一键部署

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api
