### ISSUE TITLE
[Bug] 3.1 开始没有垫图按钮了

### ISSUE THREAD

**Issue by qiulang** [Licoy/ChatGPT-Midjourney#91]
**Describe the bug**
我部署今天 3.1版本，发现没有垫图按钮了。之前 3.0.24是有的，参见截图

**Screenshots**
3.0.24 有传图片按钮
<img width="408" alt="3.0.24" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/516243/1e2903bd-d06c-4a7b-80a9-e7a6e308fb28">

3.1 没有

<img width="345" alt="3.1.0" src="https://github.com/Licoy/ChatGPT-Midjourney/assets/516243/c8bf5ab6-5bd4-4568-bca5-d3348b06c5fb">

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser [e.g. chrome, safari] Chrome
 - Version 102

**Additional Logs**
Add any logs about the problem here.

**Comment by qiulang** [comment]
试了最新 3.1.1 也没有

**Comment by Licoy** [comment]
3.x暂时都是没有的 
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/20410697/7e343185-7032-45e6-9421-0b74911a5593)

**Comment by qiulang** [comment]
可是 3.0.24 确实有啊

**Comment by qiulang** [comment]
o 我说错了 是 2.1 有

**Comment by qiulang** [comment]
这么强大功能，怎么 3.x 拿掉了

**Comment by Licoy** [comment]
不是拿掉，是框架结构改变，暂不支持，后续会陆续支持
