### ISSUE TITLE
[Bug] 频道里如果有BlueWillow bot的话，会调用BlueWillow绘图。。。导致绘图失败。

### ISSUE THREAD

**Issue by befantasy** [Licoy/ChatGPT-Midjourney#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Licoy** [comment]
对于此种错误，建议新建一个频道仅加入Midjourney机器人即可
