### ISSUE TITLE
使用mj绘画功能，经常停在进度：45%，93%这类的地方，查看discord端，图片已经画完了，但web端就停在那里了

### ISSUE THREAD

**Issue by dfggggx198601** [Licoy/ChatGPT-Midjourney#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Railway
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Licoy** [comment]
查看是不是开启了remix模式，如果是关闭再试试

**Comment by Licoy** [comment]
discord -> /setting

**Comment by dfggggx198601** [comment]
已关闭remix模式，但该问题仍然概率性存在，有时候甚至停在了任务已提交至Midjourney服务器，连进度都没有

**Comment by lovaxi** [comment]
同意，概率性出现，不太稳定。

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
