### ISSUE TITLE
[Bug] 按照readme用doker 启动项目后无法访问mj

### ISSUE THREAD

**Issue by Varian-Wrynn** [Licoy/ChatGPT-Midjourney#96]
![微信截图_20231011110346](https://github.com/Licoy/ChatGPT-Midjourney/assets/46698074/3dabfcd2-f10f-4ff9-bc5e-ccd538bfec75)
![微信截图_20231011110441](https://github.com/Licoy/ChatGPT-Midjourney/assets/46698074/e4dc7577-6baa-41e5-a1de-0fc4700b7490)
![image](https://github.com/Licoy/ChatGPT-Midjourney/assets/46698074/b44ed42a-8081-40bc-8d2b-f66f5ff98c20)

**Comment by Varian-Wrynn** [comment]
discord 服务器上没有对应任务提交记录.

**Comment by Licoy** [comment]
根据错误信息来看，意思没有提交成功，连接超时了

**Comment by 2922832737C** [comment]
请问你这问题解决了吗

**Comment by Licoy** [comment]
请使用最新的v3.3.0或以上版本，同时已经更新至chatgpt-next-web，本项目重构了绘画模块，将绘画模块进行单独页面入口区分，此issue关闭。
